#!/usr/bin/env bash
# This script lists all running processes and filters for lines containing "bash"
# shellcheck disable=SC2009
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | grep bash
